# Generated by Django 4.0.1 on 2022-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_product_updated_at_product_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%y/%m/%d'),
        ),
    ]
